version: "3"

services:
  backend:
    build:
      context: ./../backend/_
      args:
        - HOSTUID=$HOSTUID
        - HOSTGID=$HOSTGID
    volumes:
      - ./../backend:/backend
    environment:
      - FLASK_APP=/backend/flask_app.py
      - FLASK_DEBUG=1
    ports:
      - 0.0.0.0:80:5000

