"""empty message

Revision ID: e771f6f8428d
Revises: 246f8b076811
Create Date: 2017-09-30 20:42:49.493184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e771f6f8428d'
down_revision = '246f8b076811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('posts', 'pub_date', new_column_name='published_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'published_at', new_column_name='pub_date')
    op.drop_column('posts', 'meta')
    # ### end Alembic commands ###
